#!/bin/bash

# This script checks for pending video files that need to be processed and logs them.

SHARE_PATH="/usr/local/share/x265_convert_script"
#SHARE_PATH="$(pwd)"
SRC_PATH="$SHARE_PATH/src"

# Load environment variables and utility functions
if [[ -f "$SHARE_PATH/preferences.conf" ]]; then
    source "$SHARE_PATH/preferences.conf"
else
    echo "Error: preferences.conf not found in $SHARE_PATH. Exiting..."
    exit 1
fi

if [[ -f "$SRC_PATH/logging.sh" ]]; then
    source "$SRC_PATH/logging.sh"
else
    echo "Error: logging.sh not found in $SRC_PATH. Exiting..."
    exit 1
fi

if [[ -f "$SRC_PATH/file_utils.sh" ]]; then
    source "$SRC_PATH/file_utils.sh"
else
    echo "Error: file_utils.sh not found in $SRC_PATH. Exiting..."
    exit 1
fi

log "INFO" "Checking directory: ${ACTUAL_DIR}" "${REMAINING_LOG}"
if [ ! -d "${ACTUAL_DIR}" ]; then
    log "ERROR" "Error! Directory ${ACTUAL_DIR} does not exist." "${REMAINING_LOG}"
    exit 1
fi

log "INFO" "Searching for pending files..." "${REMAINING_LOG}"

files_pending=$(find_pending_files)

# Check if files have been processed and if they have the 'larger' attribute
while IFS= read -r file; do
    xattr_output=$(check_xattr_larger "$file")

    if [[ -n "$xattr_output" ]]; then
        log "DEBUG" "File $file already processed or marked as larger." "${REMAINING_LOG}"
        continue
    else
        log "INFO" "Pending file to process: $file" "${REMAINING_LOG}"
    fi
done <<< "$files_pending"

log "INFO" "Finished searching for pending files." "${REMAINING_LOG}"
